import { useEffect } from "react";
import { Navbar } from "@/components/Navbar";
import { Footer } from "@/components/Footer";
import { AlertTriangle, Stethoscope, BookOpen, ExternalLink, Info, Mail } from "lucide-react";

function Section({ icon, title, children }: { icon: React.ReactNode; title: string; children: React.ReactNode }) {
  return (
    <section className="border-b border-slate-100 pb-7 last:border-0 last:pb-0">
      <div className="flex items-center gap-3 mb-4">
        <div className="bg-amber-50 rounded-lg p-2 shrink-0">{icon}</div>
        <h2 className="text-lg font-bold text-slate-800">{title}</h2>
      </div>
      <div className="text-slate-600 text-sm leading-relaxed space-y-3 ml-11">{children}</div>
    </section>
  );
}

export function Disclaimer() {
  useEffect(() => {
    document.title = "Disclaimer | Hydration Calculator";
  }, []);

  return (
    <div className="min-h-screen bg-slate-50">
      <Navbar />

      {/* Hero */}
      <div className="bg-gradient-to-br from-amber-500 to-orange-600 text-white py-10 px-4">
        <div className="max-w-3xl mx-auto text-center">
          <div className="flex justify-center mb-4">
            <div className="bg-white/15 rounded-full p-3">
              <AlertTriangle className="w-8 h-8 text-amber-100" />
            </div>
          </div>
          <h1 className="text-3xl font-bold mb-2">Disclaimer</h1>
          <p className="text-amber-100 text-sm">Last updated: April 2026 &nbsp;·&nbsp; Hydration Calculator</p>
        </div>
      </div>

      <main className="max-w-3xl mx-auto px-4 py-10 sm:px-6">

        {/* Top Warning */}
        <div className="bg-red-50 border-2 border-red-200 rounded-2xl p-5 mb-8 flex gap-4">
          <span className="text-2xl shrink-0">🚨</span>
          <div>
            <p className="font-bold text-red-800 text-sm mb-1">Please Read Before Using</p>
            <p className="text-red-700 text-sm leading-relaxed">
              The information on this website is provided for <strong>general educational purposes only</strong>. It is <strong>not a substitute for professional medical advice, diagnosis, or treatment</strong>. Never disregard medical advice or delay seeking it because of something you read here.
            </p>
          </div>
        </div>

        <div className="bg-white rounded-2xl shadow-sm border border-slate-200 p-6 sm:p-8 space-y-7">

          <Section icon={<Stethoscope className="w-5 h-5 text-amber-600" />} title="Not Medical Advice">
            <p>The Hydration Calculator and all content on this website are for <strong>informational and educational purposes only</strong>.</p>
            <p>Nothing on this site should be considered as:</p>
            <ul className="list-disc list-inside space-y-1.5 ml-2">
              <li>Medical advice, diagnosis, or treatment</li>
              <li>A substitute for consulting a qualified doctor or healthcare professional</li>
              <li>A recommendation for any specific treatment, supplement, or health plan</li>
            </ul>
            <p>The hydration values generated by our calculator are <strong>general estimates</strong> based on widely used formulas. They are not tailored to your specific medical history, conditions, or needs.</p>
            <div className="bg-amber-50 border border-amber-200 rounded-xl p-4 mt-3">
              <p className="text-amber-800 font-semibold text-sm">👨‍⚕️ Always consult a doctor or healthcare provider</p>
              <p className="text-amber-700 text-sm mt-1">Especially if you have kidney disease, heart conditions, diabetes, are pregnant, or take medications that affect fluid balance.</p>
            </div>
          </Section>

          <Section icon={<BookOpen className="w-5 h-5 text-amber-600" />} title="For Informational Purposes Only">
            <p>All articles, tips, and content on this website are intended to provide general health information about hydration and water intake.</p>
            <p>The actual water needs of any individual depend on many factors that a general online calculator cannot fully account for, including:</p>
            <ul className="list-disc list-inside space-y-1.5 ml-2">
              <li>Specific medical conditions or diagnoses</li>
              <li>Prescription medications and their side effects</li>
              <li>Dietary habits and food water content</li>
              <li>Altitude, humidity, and individual sweat rates</li>
              <li>Age-related metabolic differences</li>
            </ul>
            <p>Use our calculator as a <strong>starting point</strong> for thinking about hydration — not as a final answer.</p>
          </Section>

          <Section icon={<Info className="w-5 h-5 text-amber-600" />} title="Accuracy of Information">
            <p>We make every reasonable effort to keep the information on this website accurate and up to date. However, we make <strong>no guarantees</strong> about the completeness, accuracy, or reliability of any content.</p>
            <p>Health and nutrition science evolves over time. What is considered best practice today may change as new research emerges. We strongly recommend cross-referencing any health information with authoritative sources such as:</p>
            <ul className="list-disc list-inside space-y-1.5 ml-2">
              <li>Your personal healthcare provider</li>
              <li>World Health Organization (WHO)</li>
              <li>National health bodies in your country</li>
              <li>Peer-reviewed scientific publications</li>
            </ul>
          </Section>

          <Section icon={<AlertTriangle className="w-5 h-5 text-amber-600" />} title="No Liability for Damages">
            <p>By using this website, you acknowledge and agree that:</p>
            <ul className="list-disc list-inside space-y-1.5 ml-2">
              <li>Hydration Calculator and its operators are <strong>not responsible</strong> for any health outcomes, injuries, or decisions you make based on this website's content</li>
              <li>We are not liable for any errors, omissions, or inaccuracies in the information provided</li>
              <li>We are not liable for any technical errors, downtime, or data loss</li>
              <li>Results from the calculator may not be suitable for everyone</li>
            </ul>
            <p>Use this website at your own risk. If you are experiencing a medical emergency, please call your local emergency services immediately.</p>
          </Section>

          <Section icon={<ExternalLink className="w-5 h-5 text-amber-600" />} title="External Links Disclaimer">
            <p>This website may contain links to external websites for reference or further reading. These links are provided as a convenience only.</p>
            <p>We have <strong>no control</strong> over the content, accuracy, or practices of external websites, and we are <strong>not responsible</strong> for:</p>
            <ul className="list-disc list-inside space-y-1.5 ml-2">
              <li>The content or views expressed on linked websites</li>
              <li>The privacy practices of external sites</li>
              <li>Any products, services, or advice offered by third parties</li>
            </ul>
            <p>Visiting external links is entirely at your own discretion. We recommend reviewing the privacy policy and terms of any external website you visit.</p>
          </Section>

          <Section icon={<Mail className="w-5 h-5 text-amber-600" />} title="Questions or Concerns">
            <p>If you have questions about this disclaimer or want to report any content you believe is inaccurate, please get in touch.</p>
            <div className="mt-2">
              <a href="/contact" className="inline-flex items-center gap-2 px-5 py-2.5 bg-amber-500 text-white rounded-xl font-bold text-sm hover:bg-amber-600 transition-colors">
                <Mail className="w-4 h-4" /> Contact Us
              </a>
            </div>
          </Section>

        </div>

        {/* Bottom note */}
        <div className="mt-6 text-center text-xs text-slate-400 leading-relaxed">
          <p>This disclaimer applies to all content on <strong>hydrationcalculator.replit.app</strong> and all associated pages.</p>
          <p className="mt-1">By using this website, you accept this disclaimer in full.</p>
        </div>

      </main>

      <Footer />
    </div>
  );
}
